// Data access for the employee portal.
// Currently an in-memory mock; when the database is added, replace these function
// bodies with calls to API routes (e.g. GET/POST /api/documents, GET /api/documents/[id]/file)
// and keep the signatures so the UI does not change.

import type { UploadInput } from "../dashboard/UploadModal";
import { mergeWipFields } from "../../lib/documentExtraction";
import { currentUser, type CategoryKey, type UserDocument } from "./userData";

const DAY = 24 * 60 * 60 * 1000;

function daysAgo(now: number, days: number): string {
  return new Date(now - days * DAY).toISOString();
}

function seedDocuments(now: number): UserDocument[] {
  return [
    {
      id: "#DOC-5520913",
      fileName: "Stena_DrillMAX_50DF_overhaul_log.pdf",
      mimeType: "application/pdf",
      sizeBytes: 2_480_000,
      category: "engine-log",
      sector: "Offshore Rig",
      vessel: "Stena DrillMAX (Offshore)",
      flag: "\u{1F1EC}\u{1F1E7}",
      flagLabel: "UK",
      engine: "Wärtsilä 50DF Main Gen",
      uploadedBy: currentUser.name,
      uploadedAt: daysAgo(now, 1),
      status: "review",
      sNo: 1,
      customer: "Stena Drilling",
      jobNo: "JOB-24-0112",
      model: "Wärtsilä 50DF",
      serialNo: "WD50-88214",
      assetId: "AST-11029",
      contactName: currentUser.name,
      jobOpeningDate: daysAgo(now, 1),
      reqNo: "REQ-5521",
      poStatus: "Pending",
      poDate: "",
      poNo: "",
      poIssuedBy: "",
      invoiceSubmissionStatus: "Not Submitted",
      paymentStatus: "Pending",
      invoiceNo: "",
      invoiceDate: "",
      swiftValue: 18500,
      idcValue: 15200,
      scopeOfWork: "Main generator overhaul & diagnostic survey",
      jobLocationReportSubmission: "Pending",
      completionReportSign: "Pending",
      jobCompletionDate: "",
      remarks: "Awaiting turbocharger spares",
      swiftFocalPoint: "Marcus Vance",
    },
    {
      id: "#DOC-1838967",
      fileName: "6S70ME-C8_crankshaft_inspection.pdf",
      mimeType: "application/pdf",
      sizeBytes: 4_120_000,
      category: "inspection",
      sector: "Marine Vessel",
      vessel: "Maersk Mc-Kinney (Tanker)",
      flag: "\u{1F1E9}\u{1F1F0}",
      flagLabel: "Denmark",
      engine: "MAN B&W 6S70ME-C8.2",
      uploadedBy: "Craig Howard",
      uploadedAt: daysAgo(now, 2),
      status: "approved",
      sNo: 2,
      customer: "Maersk Line",
      jobNo: "JOB-24-0098",
      model: "MAN B&W 6S70ME-C8.2",
      serialNo: "MB70-55310",
      assetId: "AST-10877",
      contactName: "Craig Howard",
      jobOpeningDate: daysAgo(now, 8),
      reqNo: "REQ-5478",
      poStatus: "Issued",
      poDate: daysAgo(now, 5),
      poNo: "PO-88231",
      poIssuedBy: "Maersk Procurement",
      invoiceSubmissionStatus: "Submitted",
      paymentStatus: "Pending",
      invoiceNo: "INV-33021",
      invoiceDate: daysAgo(now, 1),
      swiftValue: 42300,
      idcValue: 36900,
      scopeOfWork: "Crankshaft & bearing clearance inspection",
      jobLocationReportSubmission: "Submitted",
      completionReportSign: "Signed",
      jobCompletionDate: daysAgo(now, 2),
      remarks: "Class surveyor witnessed final checks",
      swiftFocalPoint: "Marcus Vance",
    },
    {
      id: "#DOC-2671893",
      fileName: "B32-40_cylinder_head_assembly.dwg",
      mimeType: "application/acad",
      sizeBytes: 8_950_000,
      category: "blueprint",
      sector: "Offshore Rig",
      vessel: "Bergen Rig Alpha",
      flag: "\u{1F1F3}\u{1F1F4}",
      flagLabel: "Norway",
      engine: "Rolls-Royce Bergen B32:40",
      uploadedBy: "Timothy Hines",
      uploadedAt: daysAgo(now, 3),
      status: "review",
      sNo: 3,
      customer: "Bergen Offshore AS",
      jobNo: "JOB-24-0121",
      model: "Rolls-Royce Bergen B32:40",
      serialNo: "RRB32-24471",
      assetId: "AST-11104",
      contactName: "Timothy Hines",
      jobOpeningDate: daysAgo(now, 3),
      reqNo: "REQ-5539",
      poStatus: "Not Received",
      poDate: "",
      poNo: "",
      poIssuedBy: "",
      invoiceSubmissionStatus: "Not Submitted",
      paymentStatus: "Pending",
      invoiceNo: "",
      invoiceDate: "",
      swiftValue: 9800,
      idcValue: 8100,
      scopeOfWork: "Cylinder head assembly drawing review",
      jobLocationReportSubmission: "Pending",
      completionReportSign: "Pending",
      jobCompletionDate: "",
      remarks: "Waiting on customer PO confirmation",
      swiftFocalPoint: "Edgar Humbert",
    },
    {
      id: "#DOC-9426253",
      fileName: "C32_turbo_service_bulletin.pdf",
      mimeType: "application/pdf",
      sizeBytes: 960_000,
      category: "bulletin",
      sector: "Marine Vessel",
      vessel: "CMA CGM Fort Royal",
      flag: "\u{1F1EB}\u{1F1F7}",
      flagLabel: "France",
      engine: "CAT C32 Marine Turbo",
      uploadedBy: "Lisa Collins",
      uploadedAt: daysAgo(now, 5),
      status: "approved",
      sNo: 4,
      customer: "CMA CGM",
      jobNo: "JOB-24-0083",
      model: "CAT C32 Marine Turbo",
      serialNo: "CATC32-90142",
      assetId: "AST-10655",
      contactName: "Lisa Collins",
      jobOpeningDate: daysAgo(now, 12),
      reqNo: "REQ-5390",
      poStatus: "Issued",
      poDate: daysAgo(now, 10),
      poNo: "PO-88109",
      poIssuedBy: "CMA CGM Procurement",
      invoiceSubmissionStatus: "Submitted",
      paymentStatus: "Received",
      invoiceNo: "INV-32877",
      invoiceDate: daysAgo(now, 4),
      swiftValue: 12750,
      idcValue: 10400,
      scopeOfWork: "Turbocharger service bulletin compliance check",
      jobLocationReportSubmission: "Submitted",
      completionReportSign: "Signed",
      jobCompletionDate: daysAgo(now, 5),
      remarks: "",
      swiftFocalPoint: "Marcus Vance",
    },
    {
      id: "#DOC-4819024",
      fileName: "RTA96-C_class_certificate_2024.pdf",
      mimeType: "application/pdf",
      sizeBytes: 640_000,
      category: "certificate",
      sector: "Onshore Unit",
      vessel: "Rotterdam Drydock 7",
      flag: "\u{1F1F3}\u{1F1F1}",
      flagLabel: "Netherlands",
      engine: "Sulzer RTA96-C Class Cert",
      uploadedBy: "Marcus Vance (Lead)",
      uploadedAt: daysAgo(now, 9),
      status: "verified",
      sNo: 5,
      customer: "Rotterdam Drydock Co.",
      jobNo: "JOB-24-0067",
      model: "Sulzer RTA96-C",
      serialNo: "SRTA96-77820",
      assetId: "AST-10391",
      contactName: "Marcus Vance",
      jobOpeningDate: daysAgo(now, 20),
      reqNo: "REQ-5301",
      poStatus: "Issued",
      poDate: daysAgo(now, 18),
      poNo: "PO-87980",
      poIssuedBy: "Rotterdam Drydock Co.",
      invoiceSubmissionStatus: "Submitted",
      paymentStatus: "Received",
      invoiceNo: "INV-32410",
      invoiceDate: daysAgo(now, 12),
      swiftValue: 61200,
      idcValue: 52800,
      scopeOfWork: "Class certification survey & DNV verification",
      jobLocationReportSubmission: "Submitted",
      completionReportSign: "Signed",
      jobCompletionDate: daysAgo(now, 9),
      remarks: "Verified & classed by DNV",
      swiftFocalPoint: "Marcus Vance",
    },
    {
      id: "#DOC-7310458",
      fileName: "12V32_fuel_pump_exploded_view.step",
      mimeType: "application/step",
      sizeBytes: 12_300_000,
      category: "blueprint",
      sector: "Marine Vessel",
      vessel: "Maersk Mc-Kinney (Tanker)",
      flag: "\u{1F1E9}\u{1F1F0}",
      flagLabel: "Denmark",
      engine: "Wärtsilä 12V32",
      uploadedBy: currentUser.name,
      uploadedAt: daysAgo(now, 12),
      status: "approved",
      sNo: 6,
      customer: "Maersk Line",
      jobNo: "JOB-24-0071",
      model: "Wärtsilä 12V32",
      serialNo: "W12V32-40218",
      assetId: "AST-10502",
      contactName: currentUser.name,
      jobOpeningDate: daysAgo(now, 15),
      reqNo: "REQ-5344",
      poStatus: "Issued",
      poDate: daysAgo(now, 13),
      poNo: "PO-88012",
      poIssuedBy: "Maersk Procurement",
      invoiceSubmissionStatus: "Submitted",
      paymentStatus: "Received",
      invoiceNo: "INV-32690",
      invoiceDate: daysAgo(now, 10),
      swiftValue: 7400,
      idcValue: 6100,
      scopeOfWork: "Fuel pump exploded-view drawing package",
      jobLocationReportSubmission: "Submitted",
      completionReportSign: "Signed",
      jobCompletionDate: daysAgo(now, 12),
      remarks: "",
      swiftFocalPoint: "Marcus Vance",
    },
    {
      id: "#DOC-6082741",
      fileName: "CAT3516_running_hours_Q3.xlsx",
      mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      sizeBytes: 310_000,
      category: "engine-log",
      sector: "Offshore Rig",
      vessel: "Bergen Rig Alpha",
      flag: "\u{1F1F3}\u{1F1F4}",
      flagLabel: "Norway",
      engine: "CAT 3516B Genset",
      uploadedBy: "Timothy Hines",
      uploadedAt: daysAgo(now, 16),
      status: "approved",
      sNo: 7,
      customer: "Bergen Offshore AS",
      jobNo: "JOB-24-0055",
      model: "CAT 3516B Genset",
      serialNo: "C3516B-61094",
      assetId: "AST-10218",
      contactName: "Timothy Hines",
      jobOpeningDate: daysAgo(now, 19),
      reqNo: "REQ-5288",
      poStatus: "Issued",
      poDate: daysAgo(now, 17),
      poNo: "PO-87901",
      poIssuedBy: "Bergen Offshore AS",
      invoiceSubmissionStatus: "Submitted",
      paymentStatus: "Received",
      invoiceNo: "INV-32288",
      invoiceDate: daysAgo(now, 15),
      swiftValue: 5100,
      idcValue: 4200,
      scopeOfWork: "Quarterly running hours & fuel consumption log",
      jobLocationReportSubmission: "Submitted",
      completionReportSign: "Signed",
      jobCompletionDate: daysAgo(now, 16),
      remarks: "",
      swiftFocalPoint: "Edgar Humbert",
    },
    {
      id: "#DOC-3395610",
      fileName: "Fort_Royal_DNV_hull_survey.pdf",
      mimeType: "application/pdf",
      sizeBytes: 5_700_000,
      category: "certificate",
      sector: "Marine Vessel",
      vessel: "CMA CGM Fort Royal",
      flag: "\u{1F1EB}\u{1F1F7}",
      flagLabel: "France",
      engine: "Hull & Machinery Survey",
      uploadedBy: "Lisa Collins",
      uploadedAt: daysAgo(now, 24),
      status: "verified",
      sNo: 8,
      customer: "CMA CGM",
      jobNo: "JOB-24-0031",
      model: "Hull & Machinery Survey",
      serialNo: "HMS-2024-0031",
      assetId: "AST-09984",
      contactName: "Lisa Collins",
      jobOpeningDate: daysAgo(now, 30),
      reqNo: "REQ-5190",
      poStatus: "Issued",
      poDate: daysAgo(now, 28),
      poNo: "PO-87604",
      poIssuedBy: "CMA CGM Procurement",
      invoiceSubmissionStatus: "Submitted",
      paymentStatus: "Received",
      invoiceNo: "INV-31820",
      invoiceDate: daysAgo(now, 25),
      swiftValue: 15600,
      idcValue: 13000,
      scopeOfWork: "DNV hull & machinery class survey",
      jobLocationReportSubmission: "Submitted",
      completionReportSign: "Signed",
      jobCompletionDate: daysAgo(now, 24),
      remarks: "Verified & classed by DNV",
      swiftFocalPoint: "Marcus Vance",
    },
  ];
}

let store: UserDocument[] | null = null;

export async function listDocuments(): Promise<UserDocument[]> {
  if (!store) store = seedDocuments(Date.now());
  return [...store].sort((a, b) => b.uploadedAt.localeCompare(a.uploadedAt));
}

export async function addDocument(input: UploadInput): Promise<UserDocument> {
  const now = new Date().toISOString();
  const nextSNo = (store?.length ?? 0) + 1;
  const extracted = input.extractedFields;
  const wip = mergeWipFields(extracted, {
    contactName: currentUser.name,
    modelName: input.engineModel,
  });
  const doc: UserDocument = {
    ...wip,
    sNo: nextSNo,
    id: `#DOC-${Math.floor(1_000_000 + Math.random() * 9_000_000)}`,
    fileName: input.file.name,
    mimeType: input.file.type || "application/octet-stream",
    sizeBytes: input.file.size,
    category: (input.category as CategoryKey | null) ?? "engine-log",
    sector: extracted?.sector ?? input.sector,
    vessel: input.vesselName,
    engine: input.engineModel,
    uploadedBy: currentUser.name,
    uploadedAt: now,
    status: "review",
    objectUrl: URL.createObjectURL(input.file),
  };
  store = [doc, ...(store ?? [])];
  return doc;
}

// Returns the file contents to download. Mock seed documents have no stored file,
// so a placeholder text file with their metadata is generated instead.
export async function getDocumentFile(doc: UserDocument): Promise<{ url: string; fileName: string; revoke: boolean }> {
  if (doc.objectUrl) return { url: doc.objectUrl, fileName: doc.fileName, revoke: false };

  const text = [
    "IDC Swift — placeholder download (mock data, no stored file yet)",
    "",
    `Document ID: ${doc.id}`,
    `File name:   ${doc.fileName}`,
    `Vessel:      ${doc.vessel}`,
    `Engine:      ${doc.engine}`,
    `Uploaded by: ${doc.uploadedBy}`,
    `Uploaded at: ${doc.uploadedAt}`,
  ].join("\n");
  const blob = new Blob([text], { type: "text/plain" });
  return { url: URL.createObjectURL(blob), fileName: `${doc.fileName}.txt`, revoke: true };
}

export async function downloadDocument(doc: UserDocument): Promise<void> {
  const { url, fileName, revoke } = await getDocumentFile(doc);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  a.remove();
  if (revoke) window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}
